<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPBYMINW1873" name="CalculatorPowerTest" tests="4" failures="2" timestamp="20 Dec 2017 07:37:52 GMT" time="0.000" errors="0">
  <testcase name="PowerVerivfication" time="0.000" classname="CalculatorPowerTest">
    <failure type="java.lang.AssertionError" message="expected [0.7561436672967865] but found [0.8338593590405347]">
      <![CDATA[java.lang.AssertionError: expected [0.7561436672967865] but found [0.8338593590405347]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:209)
	at org.testng.Assert.assertEquals(Assert.java:222)
	at CalculatorPowerTest.PowerVerivfication(CalculatorPowerTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- PowerVerivfication -->
  <testcase name="PowerVerivfication" time="0.000" classname="CalculatorPowerTest"/>
  <testcase name="PowerVerivfication" time="0.000" classname="CalculatorPowerTest"/>
  <testcase name="PowerVerivfication" time="0.000" classname="CalculatorPowerTest">
    <failure type="java.lang.AssertionError" message="expected [1.3224999999999998] but found [2.65]">
      <![CDATA[java.lang.AssertionError: expected [1.3224999999999998] but found [2.65]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:209)
	at org.testng.Assert.assertEquals(Assert.java:222)
	at CalculatorPowerTest.PowerVerivfication(CalculatorPowerTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- PowerVerivfication -->
</testsuite> <!-- CalculatorPowerTest -->
